### PR TITLE
New version from Flashbeing

### PR DESCRIPTION
**Pull request by useppi**
Flashbeing sent me a new version of the Free Software Lab which I have to push online

### CODE REVIEW

**Comment by ohnewein** [comment]
The repository is public now. Flashbeing should do future pull requests directly by their own.

**Comment by useppi** [comment]
yes, today we already discussed this with Flashbeing so that in future they'll do it directly

**Comment by bertolla** [comment]
I guess the pull-request is failing the CI because it didn't get rebased on the main repo.

**Comment by useppi** [comment]
@bertolla do I have to do something?

**Pull request merged**
